import assert from "node:assert/strict";
import { cp, mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import { after, before, describe, it } from "node:test";

describe("planning service (offline)", async () => {
  const sourceRoot=process.cwd(); let root=""; let template:Record<string,unknown>;
  before(async()=>{root=await mkdtemp(resolve(tmpdir(),"amiral-planning-"));await cp(resolve(sourceRoot,"team.yaml"),resolve(root,"team.yaml"));await cp(resolve(sourceRoot,".opencode","schemas"),resolve(root,".opencode","schemas"),{recursive:true});await mkdir(resolve(root,"input"),{recursive:true});template=JSON.parse(await readFile(resolve(sourceRoot,"examples","planner-result.example.json"),"utf8"));process.chdir(root);});
  after(()=>process.chdir(sourceRoot));
  const plan=(goal="Goal",type="feature")=>JSON.stringify({...template,goal,workflow_type:type});
  const transport=(outputs:Array<{exitCode?:number;stdout:string;stderr?:string}>,prompts:string[]=[] )=>({runPrompt:async(input:{prompt:string})=>{prompts.push(input.prompt);const value=outputs.shift()!;return{exitCode:value.exitCode??0,stdout:value.stdout,stderr:value.stderr??""};}});
  const enableUi=async()=>{const file=resolve(root,"team.yaml");const yaml=await readFile(file,"utf8");await writeFile(file,yaml.replace("ui:\n  enabled: false","ui:\n  enabled: true"));};

  it("accepts direct, fenced, and embedded provider JSON",async()=>{const s=await import("../scripts/lib/planning-service.js");for(const output of [plan(),`\`\`\`json\n${plan()}\n\`\`\``,`Here is the plan: ${plan()} done`]){const r=await s.planWorkflow({type:"feature",goal:"Goal",transport:transport([{stdout:output}])});assert.equal(r.plannerResult.goal,"Goal");}});
  it("always invokes the dedicated non-interactive protocol agent",async()=>{const s=await import("../scripts/lib/planning-service.js");let identity="";await s.planWorkflow({type:"feature",goal:"Goal",transport:{runPrompt:async(input)=>{identity=input.agent;return{exitCode:0,stdout:plan(),stderr:""};}}});assert.equal(identity,s.PLANNING_PROTOCOL_AGENT);assert.equal(identity,"planning-protocol");});
  it("recovers conversational-no-JSON and schema-invalid output",async()=>{const s=await import("../scripts/lib/planning-service.js");const prompts:string[]=[];const r=await s.planWorkflow({type:"bugfix",goal:"Fix login",transport:transport([{stdout:"Can you clarify?"},{stdout:'{"goal":"Fix login","summary":"x","tasks":[]}'},{stdout:plan("Fix login","bugfix")}],prompts)});assert.equal(r.plannerResult.goal,"Fix login");assert.equal(prompts.length,3);});
  it("canonicalizes model-altered authoritative metadata without retry",async()=>{const s=await import("../scripts/lib/planning-service.js");const prompts:string[]=[];const r=await s.planWorkflow({type:"refactor",goal:"Login cleanup",transport:transport([{stdout:plan("# Login cleanup","feature")}],prompts)});assert.equal(r.plannerResult.goal,"Login cleanup");assert.equal(r.plannerResult.workflow_type,"refactor");assert.equal(prompts.length,1);assert.match(prompts[0],/workflow type is authoritative/i);});
  it("preserves an explicit bug request instead of its derived title",async()=>{const s=await import("../scripts/lib/planning-service.js");const prompts:string[]=[];const request="Fix login: preserve the 401 response and redact tokens from diagnostics.";const r=await s.planWorkflow({type:"bugfix",goal:"Fix login",name:"login-fix",originalRequest:request,transport:transport([{stdout:plan("Fix login","feature")}],prompts)});assert.equal(r.plannerResult.goal,request);assert.match(prompts[0],new RegExp(request.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(prompts[0],/## Workflow Type\s+bugfix/);});
  it("preserves request through the production CLI option adapter",async()=>{const {planningOptionsFromCli}=await import("../src/cli/commands/plan.js");const s=await import("../scripts/lib/planning-service.js");const prompts:string[]=[];const request="Title plus complete description, constraints, intake, and expected behavior.";const options=planningOptionsFromCli("Derived title",{type:"bugfix",request,name:"short-name"});const r=await s.planWorkflow({...options,transport:transport([{stdout:plan()}],prompts)});assert.equal(r.plannerResult.goal,request);assert.ok(prompts[0].includes(request));assert.doesNotMatch(prompts[0],/Original User Request[^]*Derived title/);});
  it("sends a long detailed original request without truncation",async()=>{const s=await import("../scripts/lib/planning-service.js");const request=`Title: Import recovery\nDescription: ${"retain every constraint; ".repeat(200)}\nAcceptance: no data loss`;const prompts:string[]=[];await s.planWorkflow({type:"bugfix",goal:"Import recovery",originalRequest:request,transport:transport([{stdout:plan()}],prompts)});assert.ok(prompts[0].includes(request));});
  it("keeps legacy type and goal callers compatible",async()=>{const s=await import("../scripts/lib/planning-service.js");const r=await s.planWorkflow({type:"feature",goal:"Legacy goal",transport:transport([{stdout:plan()}])});assert.equal(r.plannerResult.goal,"Legacy goal");});
  it("selects a later valid plan from noisy multiple JSON objects",async()=>{const s=await import("../scripts/lib/planning-service.js");const noise='diagnostic {"message":"brace } in string"} then '+plan("Valid");const r=await s.planWorkflow({type:"feature",goal:"Authoritative",transport:transport([{stdout:noise}])});assert.equal(r.plannerResult.goal,"Authoritative");});
  it("selects a valid fenced plan after unmatched malformed brace noise",async()=>{const s=await import("../scripts/lib/planning-service.js");const output=`log { malformed\n\`\`\`json\n${plan()}\n\`\`\``;const r=await s.planWorkflow({type:"bugfix",goal:"Full bug request",transport:transport([{stdout:output}])});assert.equal(r.plannerResult.goal,"Full bug request");});
  it("reports predictable extraction diagnostics for non-JSON",async()=>{const s=await import("../scripts/lib/planning-service.js");await assert.rejects(s.planWorkflow({type:"feature",goal:"Goal",transport:transport([{stdout:"plain text"},{stdout:"plain text"},{stdout:"plain text"}])}),/recovery exhausted.*Could not extract a complete JSON object.*Diagnostics saved/i);});
  it("bounds and sanitizes the final recovery error",async()=>{const s=await import("../scripts/lib/planning-service.js");const malformed=JSON.parse(plan());malformed.tasks[0].id=`api_key=final-secret-${"x".repeat(3000)}`;delete malformed.tasks[0].description;let error:unknown;try{await s.planWorkflow({type:"feature",goal:"Goal",transport:transport([{stdout:JSON.stringify(malformed)},{stdout:JSON.stringify(malformed)},{stdout:JSON.stringify(malformed)}])});}catch(value){error=value;}assert.ok(error instanceof Error);assert.doesNotMatch(error.message,/final-secret/);assert.match(error.message,/REDACTED/);assert.ok(error.message.length<1500);});
  it("does not let metadata canonicalization bypass malformed task validation",async()=>{const s=await import("../scripts/lib/planning-service.js");const malformed=JSON.parse(plan("# Goal","bugfix"));delete malformed.tasks[0].description;let calls=0;const r=await s.planWorkflow({type:"feature",goal:"Goal",transport:{runPrompt:async()=>({exitCode:0,stdout:++calls===1?JSON.stringify(malformed):plan("changed again","refactor"),stderr:""})}});assert.equal(calls,2);assert.equal(r.plannerResult.goal,"Goal");assert.equal(r.plannerResult.workflow_type,"feature");});
  it("exhausts exactly three invalid successful responses",async()=>{const s=await import("../scripts/lib/planning-service.js");let calls=0;await assert.rejects(s.planWorkflow({type:"feature",goal:"Goal",transport:{runPrompt:async()=>{calls++;return{exitCode:0,stdout:'{"goal":',stderr:""};}}}),/recovery exhausted.*diagnostics/i);assert.equal(calls,3);});
  it("fails a nonzero provider response immediately",async()=>{const s=await import("../scripts/lib/planning-service.js");let calls=0;await assert.rejects(s.planWorkflow({type:"feature",goal:"Goal",transport:{runPrompt:async()=>{calls++;return{exitCode:1,stdout:"",stderr:"failed"};}}}),/Planner failed/);assert.equal(calls,1);});
  it("retries retryable transport failures without consuming protocol corrections",async()=>{const s=await import("../scripts/lib/planning-service.js");let calls=0;const delays:number[]=[];const outputs=[{exitCode:1,stdout:"",stderr:"HTTP 503 service unavailable"},{exitCode:0,stdout:"not json",stderr:""},{exitCode:1,stdout:"",stderr:"429 too many requests"},{exitCode:0,stdout:plan(),stderr:""}];const r=await s.planWorkflow({type:"feature",goal:"Goal",transport:{runPrompt:async()=>outputs[calls++]},delay:async value=>{delays.push(value);},random:()=>0.5});assert.equal(r.plannerResult.goal,"Goal");assert.equal(calls,4);assert.deepEqual(delays,[2000,2000]);});
  it("exhausts the transport budget independently and never protocol-retries",async()=>{const s=await import("../scripts/lib/planning-service.js");let calls=0;let delays=0;await assert.rejects(s.planWorkflow({type:"feature",goal:"Goal",transport:{runPrompt:async()=>{calls++;return{exitCode:1,stdout:"",stderr:"HTTP 503"};}},delay:async()=>{delays++;},random:()=>0.5}),/Planner failed/);assert.equal(calls,3);assert.equal(delays,2);});
  it("bounds and redacts common and multiline credentials",async()=>{const s=await import("../scripts/lib/planning-service.js");const secret='{"token":"json-secret","api_key":"api-secret","password":"multi\nline-secret"}\nAuthorization: Bearer bearer-secret\nclient_secret=client-secret\n-----BEGIN PRIVATE KEY-----\nprivate-secret\n-----END PRIVATE KEY-----\n'+"x".repeat(6000);let error:unknown;try{await s.planWorkflow({type:"feature",goal:"Goal",name:"redaction",transport:transport([{stdout:secret},{stdout:secret},{stdout:secret}])});}catch(e){error=e;}assert.ok(error);const dirs=await import("node:fs/promises").then(fs=>fs.readdir(resolve(root,"plans")));const latest=dirs.find(name=>name.startsWith("redaction-"))!;const text=await readFile(resolve(root,"plans",latest,"planner-diagnostics.json"),"utf8");for(const value of ["json-secret","api-secret","line-secret","bearer-secret","client-secret","private-secret"])assert.doesNotMatch(text,new RegExp(value));assert.match(text,/REDACTED/);assert.ok(text.length<15000);});
  it("keeps plan-file compatibility for direct, fenced, embedded, and normalizable plans",async()=>{const s=await import("../scripts/lib/planning-service.js");const normalizable=JSON.parse(plan());delete normalizable.tasks[0].dependencies;normalizable.tasks[0].acceptance_criteria.push("  extra  ","  extra  ");for(const [name,value] of [["direct",JSON.stringify(normalizable)],["fenced",`\`\`\`json\n${plan()}\n\`\`\``],["embedded",`result: ${plan()} thanks`]]){const file=resolve(root,"input",`${name}.txt`);await writeFile(file,value);const r=await s.planWorkflow({type:"feature",goal:"",planFile:file});assert.ok(r.plannerResult.tasks.length);}});
  it("rejects an invalid plan file before creating artifacts",async()=>{const s=await import("../scripts/lib/planning-service.js");const file=resolve(root,"input","invalid.json");await writeFile(file,'{"goal":"x","summary":"x","tasks":[]}');const count=(await import("node:fs/promises").then(fs=>fs.readdir(resolve(root,"plans")))).length;await assert.rejects(s.planWorkflow({type:"feature",goal:"",planFile:file}),/non-empty|fewer than 1/i);assert.equal((await import("node:fs/promises").then(fs=>fs.readdir(resolve(root,"plans")))).length,count);});
  it("does not create a plan directory for an empty live goal",async()=>{const s=await import("../scripts/lib/planning-service.js");const before=(await import("node:fs/promises")).readdir(resolve(root,"plans"));const count=(await before).length;await assert.rejects(s.planWorkflow({type:"feature",goal:""}),/non-empty goal/);assert.equal((await import("node:fs/promises").then(fs=>fs.readdir(resolve(root,"plans")))).length,count);});
  it("creates and references a corrected design spec before meaningful UI planning",async()=>{await enableUi();const s=await import("../scripts/lib/planning-service.js");const calls:Array<{agent:string;prompt:string}>=[];const spec={version:1,name:"Account dashboard",summary:"Preserve the system while adding a responsive hierarchy.",routes:[{path:"/account",description:"Responsive account dashboard with loading and error states.",acceptance_criteria:["Navigation remains keyboard accessible."]}]};const frontend=JSON.parse(plan());frontend.tasks[0].agent="frontend";let designerCalls=0;const provider={runPrompt:async(input:{agent:string;prompt:string})=>{calls.push(input);if(input.agent==="uiux-designer")return{exitCode:0,stdout:++designerCalls===1?'{"version":1}':JSON.stringify(spec),stderr:""};const match=input.prompt.match(/plans\/[^\s]+\/uiux-design-spec\.json/);frontend.tasks[0].artifact_refs=[match![0]];return{exitCode:0,stdout:JSON.stringify(frontend),stderr:""};}};const r=await s.planWorkflow({type:"feature",goal:"Build a responsive account dashboard page with accessible navigation",transport:provider});assert.deepEqual(calls.map(call=>call.agent),["uiux-designer","uiux-designer","planning-protocol"]);assert.match(calls[0].prompt,/ui-ux-pro/);assert.match(calls[1].prompt,/Previous output was rejected/);assert.match(calls[2].prompt,/uiux-design-spec\.json/);assert.equal(JSON.parse(await readFile(r.artifactFiles.designSpec!,"utf8")).name,"Account dashboard");assert.equal(JSON.parse(await readFile(r.artifactFiles.designDiagnostics!,"utf8")).length,2);assert.deepEqual(r.taskGraph.tasks[0].artifact_refs,[`plans/${r.planId}/uiux-design-spec.json`]);});
  it("does not invoke UI support for backend-only or trivial copy work",async()=>{const s=await import("../scripts/lib/planning-service.js");for(const goal of ["Add a backend REST API endpoint and database migration","Fix a spelling typo in button copy only"]){const agents:string[]=[];await s.planWorkflow({type:"feature",goal,transport:{runPrompt:async(input)=>{agents.push(input.agent);return{exitCode:0,stdout:plan(),stderr:""};}}});assert.deepEqual(agents,["planning-protocol"]);}});
});
