import assert from "node:assert/strict";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync, mkdirSync, symlinkSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, it } from "node:test";
import { assertTargetBeneathRoot, initAmiralProject } from "../scripts/lib/project-init.js";

const temporary = () => mkdtempSync(join(tmpdir(), "amiral-init-"));
describe("project-init", () => {
  it("creates the full layout and exactly one marker block", async () => { const root = temporary(); try { mkdirSync(join(root, ".git")); await initAmiralProject({ root }); assert.ok(existsSync(join(root, "team.yaml"))); assert.ok(existsSync(join(root, ".opencode", "schemas"))); assert.ok(existsSync(join(root, ".opencode", "workflows"))); await initAmiralProject({ root }); assert.equal((readFileSync(join(root, ".gitignore"), "utf8").match(/# >>> Amiral >>>/g) ?? []).length, 1); } finally { rmSync(root, { recursive: true, force: true }); } });
  it("preserves edits unless force is set", async () => { const root = temporary(); try { await initAmiralProject({ root }); const file = join(root, "team.yaml"); writeFileSync(file, "user edit\n"); await initAmiralProject({ root }); assert.equal(readFileSync(file, "utf8"), "user edit\n"); await initAmiralProject({ root, force: true }); assert.notEqual(readFileSync(file, "utf8"), "user edit\n"); } finally { rmSync(root, { recursive: true, force: true }); } });
  it("minimal includes essentials, omits agents, and warns without git", async () => { const root = temporary(); try { const result = await initAmiralProject({ root, minimal: true }); assert.ok(result.gitWarning); assert.ok(existsSync(join(root, "team.yaml"))); assert.ok(existsSync(join(root, ".opencode", "schemas"))); assert.ok(existsSync(join(root, ".opencode", "workflows"))); assert.equal(existsSync(join(root, ".opencode", "agents")), false); } finally { rmSync(root, { recursive: true, force: true }); } });
  it("rejects lexical traversal", () => { const root=temporary(); try { assert.throws(()=>assertTargetBeneathRoot(root,join(root,"..","outside")),/escapes/); } finally { rmSync(root,{recursive:true,force:true}); } });
  it("never follows an existing symlink destination", async t => { const root=temporary(), outside=temporary(); const sentinel=join(outside,"sentinel"); writeFileSync(sentinel,"safe"); try { try { symlinkSync(sentinel,join(root,"team.yaml"),"file"); } catch(error) { if (["EPERM","EACCES"].includes((error as NodeJS.ErrnoException).code??"")) { t.skip("OS denied symlink creation"); return; } throw error; } await assert.rejects(()=>initAmiralProject({root,force:true}),/symbolic link/); assert.equal(readFileSync(sentinel,"utf8"),"safe"); } finally { rmSync(root,{recursive:true,force:true}); rmSync(outside,{recursive:true,force:true}); } });
  it("rejects a nested symlink parent", async t => { const root=temporary(), outside=temporary(); try { mkdirSync(join(root,".opencode")); try { symlinkSync(outside,join(root,".opencode","schemas"),"junction"); } catch(error) { if (["EPERM","EACCES"].includes((error as NodeJS.ErrnoException).code??"")) { t.skip("OS denied link creation"); return; } throw error; } await assert.rejects(()=>initAmiralProject({root}),/symbolic link/); } finally { rmSync(root,{recursive:true,force:true}); rmSync(outside,{recursive:true,force:true}); } });
});
