import assert from "node:assert/strict";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync, mkdirSync, symlinkSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, it } from "node:test";
import { assertTargetBeneathRoot, collectFiles, copyFileSafely, initAmiralProject } from "../scripts/lib/project-init.js";

const temporary = () => mkdtempSync(join(tmpdir(), "amiral-init-"));
describe("project-init", () => {
  it("creates the full layout, bundled skills, and exactly one marker block", async () => { const root = temporary(); try { mkdirSync(join(root, ".git")); await initAmiralProject({ root }); assert.ok(existsSync(join(root, "team.yaml"))); assert.ok(existsSync(join(root, ".opencode", "schemas"))); assert.ok(existsSync(join(root, ".opencode", "workflows"))); assert.ok(existsSync(join(root, ".opencode", "agents", "uiux-designer.md"))); assert.ok(existsSync(join(root, "vendor", "skills", "using-agent-skills", "SKILL.md"))); assert.ok(existsSync(join(root, "vendor", "skills", "ui-ux-pro", "SKILL.md"))); await initAmiralProject({ root }); assert.equal((readFileSync(join(root, ".gitignore"), "utf8").match(/# >>> Amiral >>>/g) ?? []).length, 1); } finally { rmSync(root, { recursive: true, force: true }); } });
  it("preserves edits unless force is set", async () => { const root = temporary(); try { await initAmiralProject({ root }); const file = join(root, "team.yaml"); writeFileSync(file, "user edit\n"); await initAmiralProject({ root }); assert.equal(readFileSync(file, "utf8"), "user edit\n"); await initAmiralProject({ root, force: true }); assert.notEqual(readFileSync(file, "utf8"), "user edit\n"); } finally { rmSync(root, { recursive: true, force: true }); } });
  it("preserves and force-restores an installed bundled skill with POSIX steps", async () => { const root = temporary(); try { const skillPath = "vendor/skills/using-agent-skills/SKILL.md"; const installed = join(root, ...skillPath.split("/")); const initial = await initAmiralProject({ root }); const canonical = readFileSync(installed, "utf8"); assert.ok(initial.steps.some(step => step.path === skillPath && step.action === "created")); writeFileSync(installed, "user skill edit\n"); const preserved = await initAmiralProject({ root }); assert.equal(readFileSync(installed, "utf8"), "user skill edit\n"); assert.ok(preserved.steps.some(step => step.path === skillPath && step.action === "exists")); const restored = await initAmiralProject({ root, force: true }); assert.equal(readFileSync(installed, "utf8"), canonical); assert.ok(restored.steps.some(step => step.path === skillPath && step.action === "overwritten")); assert.ok(restored.steps.every(step => !step.path.includes("\\"))); } finally { rmSync(root, { recursive: true, force: true }); } });
  it("minimal includes only its existing essentials and excludes UI assets", async () => { const root = temporary(); try { const result = await initAmiralProject({ root, minimal: true }); assert.ok(result.gitWarning); assert.ok(existsSync(join(root, "team.yaml"))); assert.ok(existsSync(join(root, ".opencode", "schemas"))); assert.ok(existsSync(join(root, ".opencode", "workflows"))); assert.ok(existsSync(join(root, ".opencode", "agents", "planning-protocol.md"))); assert.equal(existsSync(join(root, ".opencode", "opencode.json")), false); assert.equal(existsSync(join(root, ".opencode", "agents", "planner.md")), false); assert.equal(existsSync(join(root, ".opencode", "agents", "uiux-designer.md")), false); assert.equal(existsSync(join(root, "vendor", "skills")), false); } finally { rmSync(root, { recursive: true, force: true }); } });
  it("collects files in deterministic POSIX order without following symlinks", async t => { const source=temporary(), outside=temporary(); try { mkdirSync(join(source,"z")); writeFileSync(join(source,"z","b.txt"),"b"); writeFileSync(join(source,"a.txt"),"a"); try { symlinkSync(outside,join(source,"linked"),"junction"); } catch(error) { if (["EPERM","EACCES"].includes((error as NodeJS.ErrnoException).code??"")) { t.skip("OS denied link creation"); return; } throw error; } writeFileSync(join(outside,"secret.txt"),"secret"); assert.deepEqual((await collectFiles(source)).map(file=>file.relativePath),["a.txt","z/b.txt"]); } finally { rmSync(source,{recursive:true,force:true}); rmSync(outside,{recursive:true,force:true}); } });
  it("rejects a symlink collection source root", async t => { const parent=temporary(), source=temporary(); const linkedRoot=join(parent,"linked-root"); try { try { symlinkSync(source,linkedRoot,"junction"); } catch(error) { if (["EPERM","EACCES"].includes((error as NodeJS.ErrnoException).code??"")) { t.skip("OS denied symlink creation"); return; } throw error; } await assert.rejects(collectFiles(linkedRoot),/symbolic link source/); } finally { rmSync(parent,{recursive:true,force:true}); rmSync(source,{recursive:true,force:true}); } });
  it("safe copy supports a destination prefix, preserves files, and force overwrites", async () => { const source=temporary(), root=temporary(); try { const input=join(source,"item.txt"); writeFileSync(input,"one"); const file={relativePath:"item.txt",absolutePath:input}; assert.equal((await copyFileSafely(file,root,false,"vendor/skills")).path,"vendor/skills/item.txt"); writeFileSync(join(root,"vendor","skills","item.txt"),"user"); assert.equal((await copyFileSafely(file,root,false,"vendor/skills")).action,"exists"); assert.equal(readFileSync(join(root,"vendor","skills","item.txt"),"utf8"),"user"); assert.equal((await copyFileSafely(file,root,true,"vendor/skills")).action,"overwritten"); assert.equal(readFileSync(join(root,"vendor","skills","item.txt"),"utf8"),"one"); await assert.rejects(copyFileSafely(file,root,false,"../outside"),/escapes/); } finally { rmSync(source,{recursive:true,force:true}); rmSync(root,{recursive:true,force:true}); } });
  it("rejects lexical traversal", () => { const root=temporary(); try { assert.throws(()=>assertTargetBeneathRoot(root,join(root,"..","outside")),/escapes/); } finally { rmSync(root,{recursive:true,force:true}); } });
  it("never follows an existing symlink destination", async t => { const root=temporary(), outside=temporary(); const sentinel=join(outside,"sentinel"); writeFileSync(sentinel,"safe"); try { try { symlinkSync(sentinel,join(root,"team.yaml"),"file"); } catch(error) { if (["EPERM","EACCES"].includes((error as NodeJS.ErrnoException).code??"")) { t.skip("OS denied symlink creation"); return; } throw error; } await assert.rejects(()=>initAmiralProject({root,force:true}),/symbolic link/); assert.equal(readFileSync(sentinel,"utf8"),"safe"); } finally { rmSync(root,{recursive:true,force:true}); rmSync(outside,{recursive:true,force:true}); } });
  it("rejects a nested symlink parent", async t => { const root=temporary(), outside=temporary(); try { mkdirSync(join(root,".opencode")); try { symlinkSync(outside,join(root,".opencode","schemas"),"junction"); } catch(error) { if (["EPERM","EACCES"].includes((error as NodeJS.ErrnoException).code??"")) { t.skip("OS denied link creation"); return; } throw error; } await assert.rejects(()=>initAmiralProject({root}),/symbolic link/); } finally { rmSync(root,{recursive:true,force:true}); rmSync(outside,{recursive:true,force:true}); } });
});
