import { createInterface } from "node:readline/promises"; import { stdin, stdout } from "node:process"; import type { Command } from "commander"; import { enterProjectContext, globalOptions, withLock } from "../context.js"; import { UsageCliError } from "../errors.js"; import { Output } from "../ui/output.js";
async function confirm(force?: boolean) { if (force) return; if (!stdin.isTTY || !stdout.isTTY) throw new UsageCliError("Confirmation requires a TTY; pass --force to continue."); const rl=createInterface({input:stdin,output:stdout}); try { if (!/^y(es)?$/i.test(await rl.question("Continue? [y/N] "))) throw new UsageCliError("Cancelled."); } finally { rl.close(); } }
export function registerWorkflow(program: Command) { const root=program.command("workflow").description("Inspect and administer workflows");
 root.command("list").description("List workflows").action(async(_,cmd)=>{await enterProjectContext();const o=new Output(globalOptions(cmd));const a=await import("../../../scripts/lib/workflow-admin-service.js");const v=await a.listWorkflowsView();if(o.options.json)return o.json(v);o.table(["ID","STATUS","ACTIVE","UPDATED"],v.map(x=>[x.id,x.status,x.active?"yes":"",x.updatedAt??""]));});
 root.command("use <id>").description("Select active workflow").action(async(id,_,cmd)=>{await enterProjectContext();const o=new Output(globalOptions(cmd));const a=await import("../../../scripts/lib/workflow-admin-service.js");const result=await withLock("workflow use",()=>a.useWorkflow(id));o.options.json?o.json({workflowId:result}):o.success(`Using workflow ${result}.`);});
 root.command("show <id>").description("Show workflow details").option("--json").action(async(id,opts,cmd)=>{await enterProjectContext();const o=new Output({...globalOptions(cmd),...opts});const a=await import("../../../scripts/lib/workflow-admin-service.js");const v=await a.showWorkflowView(id);if(o.options.json)return o.json(v);o.section(`${v.workflowId} — ${v.status}`);o.table(["TASK","TITLE","AGENT","STATUS"],v.tasks.map(t=>[t.id,t.title,t.agent,t.status]));});
 root.command("cancel <id>").description("Cancel a workflow").option("--force").action(async(id,opts,cmd)=>{await enterProjectContext();await confirm(opts.force);const o=new Output(globalOptions(cmd));const a=await import("../../../scripts/lib/workflow-admin-service.js");const v=await withLock("workflow cancel",()=>a.cancelWorkflow(id,{force:opts.force}));o.options.json?o.json(v):o.success(`Cancelled ${v.workflowId}; released ${v.releasedLeases} lease(s).`);});
 root.command("reset-task <task-id>").description("Reset a task for manual retry").option("--workflow <id>").option("--force").action(async(id,opts,cmd)=>{await enterProjectContext();const o=new Output(globalOptions(cmd));const a=await import("../../../scripts/lib/workflow-admin-service.js");const v=await withLock("workflow reset-task",()=>a.manualRetryTask(id,{workflowId:opts.workflow,force:opts.force}));o.options.json?o.json(v):o.success(`Reset task ${v.taskId}.`);});
 root.command("history [id]").description("Show workflow history").option("--limit <n>","maximum events","20").action(async(id,opts,cmd)=>{await enterProjectContext();const limit=Number(opts.limit);if(!Number.isInteger(limit)||limit<1)throw new UsageCliError("--limit must be a positive integer.");const o=new Output(globalOptions(cmd));const a=await import("../../../scripts/lib/workflow-admin-service.js");const v=await a.historyView(id,limit);if(o.options.json)return o.json(v);o.table(["TIME","EVENT","TASK","MESSAGE"],v.map(e=>[e.timestamp,e.event,e.task_id??"",e.message??""]));}); }
